-- ============================================================
--  FoodBlog Database Setup  |  Task 2
--  Database: foodBlog
--  Run once:  source foodBlog.sql;
-- ============================================================

CREATE DATABASE IF NOT EXISTS foodBlog
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

USE foodBlog;

-- ── Users ──────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS users (
    id              INT AUTO_INCREMENT PRIMARY KEY,
    name            VARCHAR(100)  NOT NULL,
    email           VARCHAR(150)  NOT NULL UNIQUE,
    password_hash   VARCHAR(255)  NOT NULL,
    role            ENUM('admin','member') NOT NULL DEFAULT 'member',
    profile_picture VARCHAR(255)  DEFAULT NULL,
    remember_token  VARCHAR(255)  DEFAULT NULL,
    created_at      TIMESTAMP     DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ── Restaurants ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS restaurants (
    id               INT AUTO_INCREMENT PRIMARY KEY,
    name             VARCHAR(150) NOT NULL,
    location         VARCHAR(150) NOT NULL,
    area             VARCHAR(150) NOT NULL,
    short_background TEXT         NOT NULL,
    goals            TEXT         NOT NULL,
    created_at       TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ── Menu Items ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS menu_items (
    id            INT AUTO_INCREMENT PRIMARY KEY,
    restaurant_id INT            NOT NULL,
    name          VARCHAR(150)   NOT NULL,
    description   TEXT           NOT NULL,
    price         DECIMAL(10,2)  NOT NULL,
    image_path    VARCHAR(255)   DEFAULT NULL,
    created_at    TIMESTAMP      DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ── Reviews ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS reviews (
    id           INT AUTO_INCREMENT PRIMARY KEY,
    menu_item_id INT  NOT NULL,
    user_id      INT  NOT NULL,
    comment      TEXT NOT NULL,
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (menu_item_id) REFERENCES menu_items(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id)      REFERENCES users(id)      ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ── Food Experience Posts ──────────────────────────────────
CREATE TABLE IF NOT EXISTS food_experience_posts (
    id             INT AUTO_INCREMENT PRIMARY KEY,
    user_id        INT          NOT NULL,
    title          VARCHAR(200) NOT NULL,
    content        TEXT         NOT NULL,
    post_type      ENUM('restaurant','food','both') NOT NULL DEFAULT 'both',
    restaurant_id  INT          DEFAULT NULL,
    menu_item_id   INT          DEFAULT NULL,
    created_at     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id)       REFERENCES users(id)        ON DELETE CASCADE,
    FOREIGN KEY (restaurant_id) REFERENCES restaurants(id)  ON DELETE SET NULL,
    FOREIGN KEY (menu_item_id)  REFERENCES menu_items(id)   ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ── Food Experience Comments ───────────────────────────────
CREATE TABLE IF NOT EXISTS food_experience_comments (
    id         INT AUTO_INCREMENT PRIMARY KEY,
    post_id    INT  NOT NULL,
    user_id    INT  NOT NULL,
    comment    TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (post_id)  REFERENCES food_experience_posts(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id)  REFERENCES users(id)                 ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ── Seed: Admin account ────────────────────────────────────
-- Email   : tanjil@gmail.com
-- Password: 12345
-- Hash generated by: password_hash('12345', PASSWORD_DEFAULT)

DELETE FROM users WHERE email IN ('admin@foodblog.com', 'tanjil@gmail.com');

INSERT INTO users (name, email, password_hash, role) VALUES (
    'Tanjil',
    'tanjil@gmail.com',
    '$2y$10$u8DmKDHJBDMNp3mFLFW7q.tL/gTH3nMvN5FsP1sMrBm7zjGq2e5uC',
    'admin'
);

-- NOTE: If login fails, open http://localhost/task2/generate_hash.php
-- in your browser — it will create the correct hash and update the DB automatically.